// Generated by scripts/validate_harbourdesk_space_evidence.py --write-generated
// Do not edit metric values in this file by hand.
export const publicEvidence = {
  "source": {
    "r11RunId": "r11-public-release-20260929-02",
    "releaseZipSha256": "1ced6ea0cbec2039a41b1bd4974fbc2f400b7bc936ad3b05cfc6788fbd3a7449",
    "resultsSha256": "afbb56a7a399a71dc30cb82a57d831b850aeb35894fd76c03b975470758736da",
    "provenanceSha256": "2955ede8138f40e32cf8fb5f21da3cef75c88eee136dbc25036b692709d2d58e",
    "releaseCommit": "2a0c0977a39dffc7ed75be8f3915ef129649875f",
    "parentR10Commit": "4bd1b8c36202611d5503abb8536cc8e138056ce8"
  },
  "metrics": {
    "fixedReference": {
      "model": "glm-5.2",
      "passes": 43,
      "cases": 90,
      "passRate": 0.4777777777777778,
      "efficiencyStatus": "INCONCLUSIVE",
      "usageIncompleteCaseCount": 1
    },
    "challenger": {
      "model": "glm-5.1",
      "passes": 15,
      "cases": 36,
      "passRate": 0.4166666666666667,
      "baselinePasses": 16,
      "baselinePassRate": 0.4444444444444444,
      "decision": "DO_NOT_PROMOTE"
    },
    "deterministicFaults": {
      "passes": 24,
      "cases": 24,
      "passRate": 1.0
    },
    "adaptation": {
      "theoreticalReduction": 0.43815621490348156,
      "requiredTargetReduction": 0.2,
      "zeroPassLossFixedCapReduction": 0.0,
      "bestPracticalReduction": 0.01706902675254618,
      "observedPassLosses": 2,
      "policyDecision": "NO_POLICY_QUALIFIED"
    },
    "decision": {
      "finalVerdict": "INCONCLUSIVE",
      "developmentDisposition": "NO_ADAPTIVE_CANDIDATE_ADMITTED",
      "adaptiveRuntimePromotion": "REJECTED",
      "lockedPairedEvaluation": "NOT_RUN",
      "lockedCasesAccessed": 0
    }
  },
  "nonClaims": [
    "The adaptive runtime did not pass the project north star.",
    "A 20 percent final efficiency improvement was not demonstrated.",
    "Locked-set candidate quality was not measured.",
    "The challenger screen is not a universal model ranking.",
    "The 24 deterministic fault cases do not establish complete production safety.",
    "The 43.8 percent figure is theoretical development headroom, not an achieved saving.",
    "The 1.7 percent figure is a development diagnostic, not a final efficiency result."
  ]
} as const
